INSERT INTO medicines (name, dosage, use_cases) VALUES
('Paracetamol (Tablet)', '500mg', 'fever, headache, mild pain'),
('Ibuprofen (Tablet)', '200mg', 'inflammation, muscle pain, fever'),
('Amoxicillin (Capsule)', '250mg', 'bacterial infection, throat infection, ear infection'),
('Cetirizine (Tablet)', '10mg', 'allergy, skin rash, sneezing'),
('Ranitidine (Tablet)', '150mg', 'acidity, gastric ulcer, heartburn'),
('Ciprofloxacin (Tablet)', '500mg', 'urinary infection, bacterial infection'),
('Metformin (Tablet)', '500mg', 'diabetes, blood sugar regulation'),
('Aspirin (Tablet)', '75mg', 'blood thinning, heart attack prevention'),
('Levothyroxine (Tablet)', '50mcg', 'thyroid disorder'),
('Omeprazole (Capsule)', '20mg', 'acid reflux, stomach ulcer'),
('Losartan (Tablet)', '50mg', 'high blood pressure, heart protection'),
('Azithromycin (Tablet)', '500mg', 'respiratory infection, skin infection'),
('Salbutamol (Inhaler)', '2mg', 'asthma, bronchospasm'),
('Clopidogrel (Tablet)', '75mg', 'stroke prevention, blood clot prevention'),
('Atorvastatin (Tablet)', '10mg', 'cholesterol management, heart disease prevention'),
('Pantoprazole (Tablet)', '40mg', 'acid reflux, gastric ulcer'),
('Doxycycline (Capsule)', '100mg', 'bacterial infection, skin infection'),
('Diclofenac (Tablet)', '50mg', 'arthritis, pain relief'),
('Loratadine (Tablet)', '10mg', 'allergy, hay fever, skin rash'),
('Hydroxychloroquine (Tablet)', '200mg', 'malaria, autoimmune diseases'),
('Erythromycin (Tablet)', '250mg', 'respiratory infection, skin infection'),
('Furosemide (Tablet)', '40mg', 'fluid retention, high blood pressure'),
('Prednisone (Tablet)', '10mg', 'inflammation, autoimmune diseases'),
('Lisinopril (Tablet)', '10mg', 'high blood pressure, heart failure'),
('Montelukast (Tablet)', '10mg', 'asthma, allergic rhinitis'),
('Insulin Glargine (Injection)', '100 units/mL', 'diabetes'),
('Amlodipine (Tablet)', '5mg', 'high blood pressure, angina'),
('Clindamycin (Capsule)', '300mg', 'bacterial infection, skin infection'),
('Esomeprazole (Capsule)', '20mg', 'acid reflux, gastric ulcer'),
('Salmeterol (Inhaler)', '50mcg', 'asthma, chronic obstructive pulmonary disease (COPD)'),
('Hydrochlorothiazide (Tablet)', '25mg', 'high blood pressure, fluid retention'),
('Tamsulosin (Capsule)', '0.4mg', 'prostate enlargement, urination difficulty'),
('Metronidazole (Tablet)', '400mg', 'bacterial infection, protozoal infection'),
('Carbamazepine (Tablet)', '200mg', 'seizures, nerve pain'),
('Warfarin (Tablet)', '5mg', 'blood clot prevention'),
('Dextromethorphan (Syrup)', '10mg/5mL', 'cough, cold'),
('Diphenhydramine (Syrup)', '25mg/5mL', 'cold, cough, allergy'),
('Chlorpheniramine (Syrup)', '4mg/5mL', 'cold, allergy, runny nose'),
('Phenylephrine (Tablet)', '10mg', 'nasal congestion, cold'),
('Guaifenesin (Syrup)', '100mg/5mL', 'cough, chest congestion');
